ALTER TABLE filial ADD COLUMN IF NOT EXISTS cnpj VARCHAR(14);
ALTER TABLE filial ADD COLUMN IF NOT EXISTS cep VARCHAR(8);
ALTER TABLE filial ADD COLUMN IF NOT EXISTS logradouro VARCHAR(255);
ALTER TABLE filial ADD COLUMN IF NOT EXISTS numero VARCHAR(50);
ALTER TABLE filial ADD COLUMN IF NOT EXISTS complemento VARCHAR(255);
ALTER TABLE filial ADD COLUMN IF NOT EXISTS bairro VARCHAR(255);
ALTER TABLE filial ADD COLUMN IF NOT EXISTS cidade VARCHAR(255);
ALTER TABLE filial ADD COLUMN IF NOT EXISTS estado VARCHAR(2);
