ALTER TABLE usuario
ADD COLUMN IF NOT EXISTS email VARCHAR(255);

ALTER TABLE remessa
ADD COLUMN IF NOT EXISTS pdf_nome_arquivo VARCHAR(255);

ALTER TABLE remessa
ADD COLUMN IF NOT EXISTS pdf_mime_type VARCHAR(100);

ALTER TABLE remessa
ADD COLUMN IF NOT EXISTS pdf_conteudo BYTEA;

ALTER TABLE remessa
ADD COLUMN IF NOT EXISTS pdf_gerado_em TIMESTAMP;
